# if (!require("devtools")) install.packages("devtools")
# if (!require("shiny")) install.packages("shiny")
# if (!require("tidyverse")) install.packages("tidyverse")
# if (!require("shinyjs")) install.packages("shinyjs")
# if (!require("highcharter")) install.packages("highcharter")
# if (!require("hgchmagic")) devtools::install_github("randommonkey/hgchmagic")
# if (!require("geomagic")) devtools::install_github("randommonkey/geomagic")

library(shiny)
library(shinyjs)
#library(geomagic)
library(tidyverse)
library(hgchmagic)
